    CONFIG.CPM_CONFIG { \
      CPM_PCIE0_MODES                                    {None} \
      CPM_PCIE1_ACS_CAP_ON                               {0} \
      CPM_PCIE1_ARI_CAP_ENABLED                          {0} \
      CPM_PCIE1_CFG_EXT_IF                               {1} \
      CPM_PCIE1_CFG_VEND_ID                              {10ee} \
      CPM_PCIE1_COPY_PF0_QDMA_ENABLED                    {0} \
      CPM_PCIE1_EXT_PCIE_CFG_SPACE_ENABLED               {Extended_Large} \
      CPM_PCIE1_FUNCTIONAL_MODE                          {QDMA} \
      CPM_PCIE1_MAX_LINK_SPEED                           {32.0_GT/s} \
      CPM_PCIE1_MODES                                    {DMA} \
      CPM_PCIE1_MODE_SELECTION                           {Advanced} \
      CPM_PCIE1_MSI_X_OPTIONS                            {MSI-X_Internal} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_0               {0x0000008000000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_1               {0x0000008040000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_2               {0x0000008080000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_3               {0x00000080C0000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_4               {0x0000008100000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_BASEADDR_5               {0x0000008140000000} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_0               {0x000000803FFFFFFFF} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_1               {0x000000807FFFFFFFF} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_2               {0x00000080BFFFFFFFF} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_3               {0x00000080FFFFFFFFF} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_4               {0x000000813FFFFFFFF} \
      CPM_PCIE1_PF0_AXIBAR2PCIE_HIGHADDR_5               {0x000000817FFFFFFFF} \
      CPM_PCIE1_PF0_BAR0_QDMA_64BIT                      {1} \
      CPM_PCIE1_PF0_BAR0_QDMA_ENABLED                    {1} \
      CPM_PCIE1_PF0_BAR0_QDMA_PREFETCHABLE               {1} \
      CPM_PCIE1_PF0_BAR0_QDMA_SCALE                      {Megabytes} \
      CPM_PCIE1_PF0_BAR0_QDMA_SIZE                       {256} \
      CPM_PCIE1_PF0_BAR0_QDMA_TYPE                       {AXI_Bridge_Master} \
      CPM_PCIE1_PF0_BAR2_QDMA_64BIT                      {0} \
      CPM_PCIE1_PF0_BAR2_QDMA_ENABLED                    {0} \
      CPM_PCIE1_PF0_BAR2_QDMA_PREFETCHABLE               {0} \
      CPM_PCIE1_PF0_BAR2_QDMA_SCALE                      {Kilobytes} \
      CPM_PCIE1_PF0_BAR2_QDMA_SIZE                       {4} \
      CPM_PCIE1_PF0_BAR2_QDMA_TYPE                       {AXI_Bridge_Master} \
      CPM_PCIE1_PF0_BASE_CLASS_VALUE                     {12} \
      CPM_PCIE1_PF0_CFG_DEV_ID                           {50b4} \
      CPM_PCIE1_PF0_CFG_SUBSYS_ID                        {000e} \
      CPM_PCIE1_PF0_DEV_CAP_FUNCTION_LEVEL_RESET_CAPABLE {0} \
      CPM_PCIE1_PF0_MSIX_CAP_TABLE_OFFSET                {40} \
      CPM_PCIE1_PF0_MSIX_CAP_TABLE_SIZE                  {1} \
      CPM_PCIE1_PF0_MSIX_ENABLED                         {0} \
      CPM_PCIE1_PF0_PCIEBAR2AXIBAR_QDMA_0                {0x0000020100000000} \
      CPM_PCIE1_PF0_SUB_CLASS_VALUE                      {00} \
      CPM_PCIE1_PF1_BAR0_QDMA_64BIT                      {0} \
      CPM_PCIE1_PF1_BAR0_QDMA_ENABLED                    {0} \
      CPM_PCIE1_PF1_BAR0_QDMA_PREFETCHABLE               {0} \
      CPM_PCIE1_PF1_BAR0_QDMA_SCALE                      {Kilobytes} \
      CPM_PCIE1_PF1_BAR0_QDMA_SIZE                       {4} \
      CPM_PCIE1_PF1_BAR0_QDMA_TYPE                       {AXI_Bridge_Master} \
      CPM_PCIE1_PF1_BAR2_QDMA_64BIT                      {0} \
      CPM_PCIE1_PF1_BAR2_QDMA_ENABLED                    {0} \
      CPM_PCIE1_PF1_BAR2_QDMA_PREFETCHABLE               {0} \
      CPM_PCIE1_PF1_BAR2_QDMA_SCALE                      {Kilobytes} \
      CPM_PCIE1_PF1_BAR2_QDMA_SIZE                       {4} \
      CPM_PCIE1_PF1_BAR2_QDMA_TYPE                       {AXI_Bridge_Master} \
      CPM_PCIE1_PF1_BASE_CLASS_VALUE                     {05} \
      CPM_PCIE1_PF1_CFG_DEV_ID                           {50b5} \
      CPM_PCIE1_PF1_CFG_SUBSYS_ID                        {000e} \
      CPM_PCIE1_PF1_MSIX_CAP_TABLE_OFFSET                {50000} \
      CPM_PCIE1_PF1_MSIX_CAP_TABLE_SIZE                  {31} \
      CPM_PCIE1_PF1_PCIEBAR2AXIBAR_QDMA_2                {0x0000020200000000} \
      CPM_PCIE1_PF1_SUB_CLASS_VALUE                      {80} \
      CPM_PCIE1_PL_LINK_CAP_MAX_LINK_WIDTH               {X8} \
      CPM_PCIE1_TL_PF_ENABLE_REG                         {1} \
    } \
