/**
 * Copyright (c) 2023 Advanced Micro Devices, Inc. All rights reserved.
 * SPDX-License-Identifier: MIT
 *
 * This file contains the sensors profile for the V80
 *
 * @file profile_sensors.h
 *
 */

#ifndef _PROFILES_SENSORS_H_
#define _PROFILES_SENSORS_H_

#include "profile_muxed_device.h"

#include "asc_proxy_driver.h"
#include "ina3221.h"
#include "isl68221.h"
#include "cat34ts02.h"
#include "sys_mon.h"

#define PROFILE_SENSORS_NUM_SENSORS ( 18 )

/**
 * @brief   Wrapper for the iSYS_MON_ReadTemperature function, to keep it the standard driver API format
 *
 * @param   unused1     Unused parameter (normally i2c bus)
 * @param   unused2     Unused parameter (normally i2c address)
 * @param   unused3     Unused parameter (normally i2c channel)
 * @param   pfValue     Pointer to latest sensor value
 *
 * @return  The return value of iSYS_MON_ReadTemperature
 *
 * @note    No sanity checks, etc, are done - this function is solely a wrapper API
 */
static inline int iSYS_MON_WrappedReadTemperature( uint8_t unused1, uint8_t unused2, uint8_t unused3, float *pfValue )
{
    return iSYS_MON_ReadTemperature( pfValue );
}

/**
 * @brief   Wrapper for the iAXC_GetTemperature function, to keep it the standard driver API format
 *
 * @param   unused1      Unused parameter (normally i2c bus)
 * @param   unused2      Unused parameter (normally i2c address)
 * @param   ucChannelNum Channel Num, used to specify QSFP ID
 * @param   pfValue      Pointer to latest sensor value
 *
 * @return  OK           Data retrieved from proxy driver successfully
 *          ERROR        Data not retrieved successfully
 *
 * @note    No sanity checks, etc, are done - this function is solely a wrapper API
 */
static inline int iAXC_WrappedGetTemperature( uint8_t unused1, uint8_t unused2, uint8_t ucChannelNum, float *pfValue )
{
    int iStatus = ERROR;
    if( 0 < MAX_NUM_EXTERNAL_DEVICES_AVAILABLE )
    {
        iStatus = iAXC_GetTemperature( ucChannelNum, pfValue );
    }

    return iStatus;
}

/**
 * @brief   Wrapper for the iSYS_MON_ReadVoltage function, to keep it the standard driver API format
 *
 * @param   unused1     Unused parameter (normally i2c bus)
 * @param   unused2     Unused parameter (normally i2c address)
 * @param   ucVType     Voltage type to read (normally i2c channel)
 * @param   pfValue     Pointer to latest sensor value
 *
 * @return  The return value of iSYS_MON_WrappedReadVoltage
 *
 * @note    No sanity checks, etc, are done - this function is solely a wrapper API
 */
static inline int iSYS_MON_WrappedReadVoltage( uint8_t unused1, uint8_t unused2, uint8_t ucVType, float *pfValue )
{
    return iSYS_MON_ReadVoltage( ucVType, pfValue );
}

/**
 * @brief   Function pointer called in profile to enable sensors that are used for V80 and V80P
 *
 * @return  TRUE to indictate sensor is enabled
 */
static inline int iSensorIsEnabled( void )
{
    return TRUE;
}

/**
 * @brief   Function pointer called in profile to disable sensors that are not used for V80P
 *
 * @return  TRUE if card is V80 or FALSE if card is V80P
 */
static inline int iSensorIsEnabledOrDisabled( void )
{
    static int      iSensorEnableStatus = TRUE;
    static uint8_t  ucProductNameCheck  = FALSE;

    if( FALSE == ucProductNameCheck )
    {
        uint8_t pucField[ EEPROM_MAX_FIELD_SIZE ] = { 0 };
        uint8_t ucSizeBytes = 0;

        if( OK == iEEPROM_GetProductName( pucField, &ucSizeBytes ) )
        {
            if( ( NULL == strstr( ( char* )pucField, "v80" ) ) &&
                ( NULL == strstr( ( char* )pucField, "V80" ) ) )
            {
                if( ( NULL != strstr( ( char* )pucField, "80p" ) ) ||
                    ( NULL != strstr( ( char* )pucField, "80P" ) ) )
                {
                    /* Running on a v80p but not a v80 */
                    iSensorEnableStatus = FALSE;
                }
            }

            ucProductNameCheck = TRUE;
        }
    }

    return iSensorEnableStatus;
}

ASC_PROXY_DRIVER_SENSOR_DATA PROFILE_SENSORS_SENSOR_DATA [ PROFILE_SENSORS_NUM_SENSORS ] = {
    { "PCB", 12, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE , FALSE, 0x1A, { ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iCAT34TS02_ReadTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 80, 85, 95, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "Device", 13, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE , FALSE, 0, { ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iSYS_MON_WrappedReadTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 92, 100, 105, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "VCCINT", 14, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT, FALSE, 0x60, { 0, 0, 0, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iISL68221_ReadTemperature, iISL68221_ReadVoltage, iISL68221_ReadCurrent, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 100, 110, 125, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "Module_0", 15, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE, FALSE, 0, { 1, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabledOrDisabled, { iAXC_WrappedGetTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 80, 85, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "Module_1", 16, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE, FALSE, 0, { 2, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabledOrDisabled, { iAXC_WrappedGetTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 80, 85, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "Module_2", 17, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE, FALSE, 0, { 3, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabledOrDisabled, { iAXC_WrappedGetTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 80, 85, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "Module_3", 18, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE, FALSE, 0, { 4, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabledOrDisabled, { iAXC_WrappedGetTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 80, 85, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "DIMM", 43, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE, FALSE, 0, { 5, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabledOrDisabled, { iAXC_WrappedGetTemperature, NULL, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "1V2_VCC_HBM", 20, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT, FALSE, 0x61, { 0, 0, 0, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iISL68221_ReadTemperature, iISL68221_ReadVoltage, iISL68221_ReadCurrent, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "12V_AUX1", 21, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT | ASC_PROXY_DRIVER_SENSOR_BITFIELD_POWER, TRUE, 0x41, { ASC_SENSOR_I2C_BUS_INVALID, 1, 1, 1 }, iSensorIsEnabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 12500, 12750, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "12V_AUX2", 22, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT | ASC_PROXY_DRIVER_SENSOR_BITFIELD_POWER, TRUE, 0x41, { ASC_SENSOR_I2C_BUS_INVALID, 2, 2, 2 }, iSensorIsEnabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 12500, 12750, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "1V2_VCCO_DIMM", 23, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT, FALSE, 0x41, { ASC_SENSOR_I2C_BUS_INVALID, 0, 0, 0 }, iSensorIsEnabledOrDisabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "3V3_PEX", 24, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT | ASC_PROXY_DRIVER_SENSOR_BITFIELD_POWER, TRUE, 0x40, { ASC_SENSOR_I2C_BUS_INVALID, 1, 1, 1 }, iSensorIsEnabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 3000, 3150, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "12V_PEX", 25, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT | ASC_PROXY_DRIVER_SENSOR_BITFIELD_POWER, TRUE, 0x40, { ASC_SENSOR_I2C_BUS_INVALID, 0, 0, 0 }, iSensorIsEnabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 5500, 5750, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "3V3_QSFP", 34, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT | ASC_PROXY_DRIVER_SENSOR_BITFIELD_POWER, FALSE, 0x40, { ASC_SENSOR_I2C_BUS_INVALID, 2, 2, 2 }, iSensorIsEnabledOrDisabled, { NULL, iINA3221_ReadVoltage, iINA3221_ReadCurrent, iINA3221_ReadPower }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI } }
    },
    { "1V5_VCCAUX", 36, ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE, FALSE, 0, { ASC_SENSOR_I2C_BUS_INVALID, SYS_MON_VOLTAGES_VCCAUX, ASC_SENSOR_I2C_BUS_INVALID, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { NULL, iSYS_MON_WrappedReadVoltage, NULL, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "1V2_GTXAVTT", 38, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT, FALSE, 0x61, { 2, 2, 2, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iISL68221_ReadTemperature, iISL68221_ReadVoltage, iISL68221_ReadCurrent, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    },
    { "0V88_VCC_CPM5", 41, ASC_PROXY_DRIVER_SENSOR_BITFIELD_TEMPERATURE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_VOLTAGE | ASC_PROXY_DRIVER_SENSOR_BITFIELD_CURRENT, FALSE, 0x61, { 1, 1, 1, ASC_SENSOR_I2C_BUS_INVALID }, iSensorIsEnabled, { iISL68221_ReadTemperature, iISL68221_ReadVoltage, iISL68221_ReadCurrent, NULL }, {
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_MILLI },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE },
        { 0, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, ASC_SENSOR_INVALID_VAL, 0, 0, ASC_PROXY_DRIVER_SENSOR_STATUS_NOT_PRESENT, ASC_PROXY_DRIVER_SENSOR_UNIT_MOD_NONE } }
    }
};

#endif
